# See documentation for details on definitions:
# https://rubocop.readthedocs.io

AllCops:
  DisplayCopNames: true
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'lib/tasks/circle_0.rake' # Ignore circleci code
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/DotPosition:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# Allow use of both single and double quotes for strings.
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false
