AllCops:
  UseCache: true
  MaxFilesInCache: 20000
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'data/**/*'
    - 'db/**/*'
    - 'lib/tasks/circle_0.rake'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Guardfile'

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Not:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/AlignParameters:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
  IgnoredPatterns: ['(\A|\s)#']
  Max: 100

Metrics/MethodLength:
  Max: 12

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 8
