# Ruby CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name:
          command: bundle exec bundle-audit update && bundle exec bundle-audit check
      - run:
          name: run tests
          command: bundle exec rspec
