---
name: Pipeline
on:
  - push
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.8
          bundler-cache: true
      - uses: r7kamura/rubocop-problem-matchers-action@v1
      - name: Rubocop
        run: bundle exec rubocop
      - name: Run rspec
        run: bundle exec rspec
      - name: Release the gem
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        run: |
          git config user.name "Wolfbot"
          git config user.email "noreply@wealthsimple.com"
          bundle exec rake release
        env:
          EMAIL: ${{ secrets.RUBYGEMS_EMAIL }}
          GIT_AUTHOR_NAME: Wealthsimple
          GIT_COMMITTER_NAME: Wealthsimple
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
